#!/bin/bash
#
echo "Start Build Script  $(date)"
#
script="$(readlink -f ${BASH_SOURCE[0]})"
base="$(dirname $script)"
echo "Script Name : $script"
echo "Current working dir : $PWD"
echo "Script location path (dir) : $base"
#
echo "Changing to Django Directory"
rm -rf reports
cd "$base/../Dev"
rm -rf reports
#
echo "Creating Virtual Enviroment"
#virtualenv env --python=python
#env/bin/pip install -r requeriments.pip
#env/bin/python manage.py jenkins
echo "Star Jenkins+Django Test"
touch junit.xml
python ProyectosEcys/manage.py jenkins sistema_pe

#env/bin/python manage.py jenkins


echo "Copy Proyect to Dev Envioroment"
echo "Changing to www-data"
sudo -u www-data cp -rv Conf /var/www/dev.proyectos-ecys.tk/
sudo -u www-data cp -rv ProyectosEcys /var/www/dev.proyectos-ecys.tk/
echo "Moving Static Files"
sudo -u www-data rm -rf /var/www/dev.proyectos-ecys.tk/static
sudo -u www-data cp -rv /var/www/dev.proyectos-ecys.tk/ProyectosEcys/sistema_pe/static /var/www/dev.proyectos-ecys.tk/
echo "Syncing DB"
sudo -u www-data python /var/www/dev.proyectos-ecys.tk/ProyectosEcys/manage.py syncdb
echo "Starting Unit TEst"

#echo "Changing Onwer to www-data"
#chmod -R 775 /var/www/dev.proyectos-ecys.tk
#chown -R www-data /var/www/dev.proyectos-ecys.tk

echo "End Build Script $(date)"

